name: deploy application

run-name: ${{ github.actor }} is deploying project

on:
  push:
  workflow_dispatch:

jobs:
  create-folder:
    name: Create folder on server
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/ms-clinique-rabat/microservices

  build-project:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java version
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: |
          cd springBoot
          mvn clean package spring-boot:repackage -DskipTests
          ls -al target

  
