name: Deploy application

run-name: ${{ github.actor }} is deploying project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-folder:
    name: Create folder on server
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Create remote folder
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              root@${{ secrets.SERVER_HOST }} \
              "mkdir -p /opt/ms-clinique-rabat/microservices"

  build-project:
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Copy JAR to server
        run: |
          scp -i ~/.ssh/id_ed25519 \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              springBoot/target/*.jar \
              root@${{ secrets.SERVER_HOST }}:/opt/ms-clinique-rabat/microservices/
  

  run-project:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Run application via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              root@${{ secrets.SERVER_HOST }} "echo SSH OK"
