name: Deploy application

run-name: ${{ github.actor }} is deploying project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-folder:
    name: Create folder on server
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/ms-clinique-rabat/microservices

  build-project:
    name: Build Spring Boot application
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Spring Boot project
        working-directory: springBoot
        run: |
          mvn clean package spring-boot:repackage -DskipTests
          ls -al target

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: springBoot/target/GestionClinique-0.0.1-SNAPSHOT.jar
          target: /opt/ms-clinique-rabat/microservices
          overwrite: true

  run-project:
    name: Run application on server
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill -f GestionClinique-0.0.1-SNAPSHOT.jar || true

            cd /opt/ms-clinique-rabat/microservices

            nohup java -jar GestionClinique-0.0.1-SNAPSHOT.jar \
              --spring.mail.host=${{ secrets.MAIL_HOST }} \
              --spring.datasource.username=${{ secrets.DATABASE_USERNAME }} \
              --spring.datasource.password=${{ secrets.DATABASE_USERPASSWORD }} \
              --spring.datasource.url=${{ secrets.DATABASE_URL }} \
              --spring.sql.init.mode=true \
              > /var/log/ms-clinique-rabat.log 2>&1 < /dev/null &

            exit 0
